export const products = [
  {
    id: 1,
    name: "Midnight Orchid",
    description:
      "A captivating blend of rare orchid, vanilla, and amber that creates an intoxicating aura of mystery and elegance.",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=800&auto=format&fit=crop",
    category: "Women",
    featured: true,
    size: "50ml",
    notes: ["Orchid", "Vanilla", "Amber", "Musk"],
    rating: 4.8,
  },
  {
    id: 2,
    name: "Ocean Breeze",
    description:
      "A refreshing aquatic fragrance with notes of sea salt, citrus, and cedar wood, evoking the feeling of a coastal getaway.",
    price: 75.99,
    image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?q=80&w=800&auto=format&fit=crop",
    category: "Men",
    featured: true,
    size: "100ml",
    notes: ["Sea Salt", "Citrus", "Cedar", "Bergamot"],
    rating: 4.6,
  },
  {
    id: 3,
    name: "Golden Amber",
    description:
      "A warm and sensual fragrance featuring rich amber, spicy cardamom, and creamy sandalwood for a luxurious experience.",
    price: 120.0,
    image: "https://images.unsplash.com/photo-1592945403407-9caf930b2c6c?q=80&w=800&auto=format&fit=crop",
    category: "Unisex",
    featured: true,
    size: "75ml",
    notes: ["Amber", "Cardamom", "Sandalwood", "Vanilla"],
    rating: 4.9,
  },
  {
    id: 4,
    name: "Rose Velvet",
    description:
      "An elegant composition of Bulgarian rose, peony, and patchouli that embodies timeless femininity and grace.",
    price: 95.5,
    image: "https://images.unsplash.com/photo-1557170334-a9086d21c4a9?q=80&w=800&auto=format&fit=crop",
    category: "Women",
    featured: true,
    size: "50ml",
    notes: ["Rose", "Peony", "Patchouli", "Musk"],
    rating: 4.7,
  },
  {
    id: 5,
    name: "Noir Intense",
    description:
      "A bold and sophisticated fragrance with notes of leather, tobacco, and spices, perfect for the modern gentleman.",
    price: 110.0,
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?q=80&w=800&auto=format&fit=crop",
    category: "Men",
    featured: true,
    size: "100ml",
    notes: ["Leather", "Tobacco", "Spices", "Vetiver"],
    rating: 4.8,
  },
  {
    id: 6,
    name: "Citrus Bloom",
    description:
      "A vibrant blend of zesty citrus, jasmine, and white musk that brings a refreshing energy to any occasion.",
    price: 65.99,
    image: "https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?q=80&w=800&auto=format&fit=crop",
    category: "Unisex",
    featured: true,
    size: "75ml",
    notes: ["Lemon", "Bergamot", "Jasmine", "White Musk"],
    rating: 4.5,
  },
  {
    id: 7,
    name: "Velvet Oud",
    description:
      "An opulent fragrance featuring rare oud wood, saffron, and rose for an unforgettable impression of luxury.",
    price: 150.0,
    image: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?q=80&w=800&auto=format&fit=crop",
    category: "Unisex",
    featured: false,
    size: "50ml",
    notes: ["Oud", "Saffron", "Rose", "Amber"],
    rating: 4.9,
  },
  {
    id: 8,
    name: "Fresh Neroli",
    description:
      "A bright and uplifting scent with neroli, bergamot, and green tea that captures the essence of a Mediterranean garden.",
    price: 79.99,
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=800&auto=format&fit=crop",
    category: "Women",
    featured: false,
    size: "75ml",
    notes: ["Neroli", "Bergamot", "Green Tea", "Jasmine"],
    rating: 4.6,
  },
  {
    id: 9,
    name: "Spiced Cedar",
    description:
      "A warm and woody fragrance with cedar, cinnamon, and tonka bean that exudes confidence and sophistication.",
    price: 85.0,
    image: "https://images.unsplash.com/photo-1605651531144-51381895e23d?q=80&w=800&auto=format&fit=crop",
    category: "Men",
    featured: false,
    size: "100ml",
    notes: ["Cedar", "Cinnamon", "Tonka Bean", "Amber"],
    rating: 4.7,
  },
  {
    id: 10,
    name: "Vanilla Dreams",
    description:
      "A comforting blend of Madagascar vanilla, caramel, and musk that wraps you in a warm and sweet embrace.",
    price: 70.0,
    image: "https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?q=80&w=800&auto=format&fit=crop",
    category: "Women",
    featured: false,
    size: "50ml",
    notes: ["Vanilla", "Caramel", "Musk", "Coconut"],
    rating: 4.5,
  },
  {
    id: 11,
    name: "Alpine Forest",
    description:
      "A crisp and invigorating fragrance with pine, juniper, and cedarwood that evokes the freshness of a mountain forest.",
    price: 80.0,
    image: "https://images.unsplash.com/photo-1605651531144-51381895e23d?q=80&w=800&auto=format&fit=crop",
    category: "Men",
    featured: false,
    size: "75ml",
    notes: ["Pine", "Juniper", "Cedarwood", "Mint"],
    rating: 4.6,
  },
  {
    id: 12,
    name: "Moonlit Jasmine",
    description:
      "An enchanting floral fragrance with jasmine, tuberose, and ylang-ylang that blooms like flowers under the moonlight.",
    price: 90.0,
    image: "https://images.unsplash.com/photo-1615484477778-ca3b77940c25?q=80&w=800&auto=format&fit=crop",
    category: "Women",
    featured: false,
    size: "50ml",
    notes: ["Jasmine", "Tuberose", "Ylang-Ylang", "Sandalwood"],
    rating: 4.8,
  },
  {
    id: 13,
    name: "Leather & Spice",
    description:
      "A bold and distinctive fragrance with leather, black pepper, and cardamom that makes a powerful statement.",
    price: 95.0,
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?q=80&w=800&auto=format&fit=crop",
    category: "Men",
    featured: false,
    size: "100ml",
    notes: ["Leather", "Black Pepper", "Cardamom", "Vetiver"],
    rating: 4.7,
  },
  {
    id: 14,
    name: "White Musk",
    description:
      "A clean and ethereal scent with white musk, lily of the valley, and cotton that feels like a second skin.",
    price: 65.0,
    image: "https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=800&auto=format&fit=crop",
    category: "Unisex",
    featured: false,
    size: "75ml",
    notes: ["White Musk", "Lily of the Valley", "Cotton", "Iris"],
    rating: 4.5,
  },
  {
    id: 15,
    name: "Exotic Saffron",
    description:
      "A luxurious and exotic fragrance with saffron, rose, and agarwood that transports you to distant lands.",
    price: 130.0,
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=800&auto=format&fit=crop",
    category: "Unisex",
    featured: false,
    size: "50ml",
    notes: ["Saffron", "Rose", "Agarwood", "Patchouli"],
    rating: 4.9,
  },
]
