import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './views/footer/footer'
import Header from './views/header/Header'


export const metadata = {
  title: 'Ezitech Institiute',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
